### PR TITLE
Use token_to_string instead of binop_to_string

### LINKED ISSUE #1887: Does not compile on 1.20.0-nightly (f85579d4a 2017-07-12)
```
error[E0603]: function `binop_to_string` is private
  --> clippy_lints-0.0.143/src/utils/sugg.rs:11:5
   |
11 | use syntax::print::pprust::binop_to_string;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by kraai**
Fixes #1887

### CODE REVIEW

**Comment by dtolnay** [comment]
Please make sure the email on this commit is associated with your GitHub account. https://github.com/settings/emails

**Comment by kraai** [comment]
I've added the email I used for the commit at the URL you sent and verified that the email address is valid.  Is there anything else I need to do?

**Comment by mcarton** [comment]
Restarting CI builds

**Comment by llogiq** [comment]
The 'errors' seem due to the fact that rustc now prints suggestions with line numbers.

**Comment by oli-obk** [comment]
oh, my other pr should fix that. I'll give it a try

**Comment by oli-obk** [comment]
I'll merge this and fix everything in the other PR
