### PR TITLE
Rustup to *rustc 1.15.0-nightly (ac635aa95 2016-11-18)* and bump to 0.0.100

### LINKED ISSUE #1350: Does not compile on rustc 1.15.0-nightly (ac635aa95 2016-11-18)
```
$ cargo build
   Compiling clippy_lints v0.0.99
error[E0308]: mismatched types
  --> clippy_lints/src/len_zero.rs:71:86
   |
71 |             ItemImpl(_, _, _, None, _, ref impl_items) => check_impl_items(cx, item, impl_items),
   |                                                                                      ^^^^^^^^^^ expected slice, found struct `syntax::ptr::P`
   |
   = note: expected type `&[rustc::hir::ImplItem]`
   = note:    found type `&syntax::ptr::P<[rustc::hir::ImplItemRef]>`

error: aborting due to previous error

error: Could not compile `clippy_lints`.

To learn more, run the command again with --verbose.

$ rustc --version
rustc 1.15.0-nightly (ac635aa95 2016-11-18)
```

### PR DESCRIPTION
**Pull request by mcarton**
Fix #1350.

:cake: :birthday: :gift: :balloon: :tada: 0.0.:100:! :tada: :balloon: :gift: :birthday: :cake:

### CODE REVIEW

**Comment by mcarton** [comment]
Such fail with the title :smile:
