### PR TITLE
Update to latest nightly

### LINKED ISSUE #1714: Compilation breakage: rustc_errors::CodeSuggestion
☔️ The latest upstream changes (presumably rust-lang/rust#40851) have made clippy unbuildable.

```
error[E0063]: missing field `msg` in initializer of `rustc_errors::CodeSuggestion`
   --> clippy_lints/src/utils/mod.rs:596:53
    |
596 |     let sugg = rustc_errors::RenderSpan::Suggestion(rustc_errors::CodeSuggestion {
    | 
```

@oli-obk wait, you made this one? probably you know what's the right way to port?

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #1714 

needs to wait for the next nightly

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
I'm quite sure that today's nightly is ready, please merge.

**Comment by ishitatsuyuki** [comment]
New failure:
```
error[E0106]: missing lifetime specifier
   --> clippy_lints/src/loops.rs:875:35
    |
875 |     indexed: HashMap<Name, Option<CodeExtent>>, // indexed variables, the extent is None for global
    |                                   ^^^^^^^^^^ expected lifetime parameter
```

**Comment by oli-obk** [comment]
Already on it :) mostly caused by https://github.com/rust-lang/rust/pull/41662

**Comment by oli-obk** [comment]
My suggestion changes made some of our suggestions ugly. I fixed some, but there are others left. I plan to improve this by both changes in rustc and in clippy.

**Comment by ishitatsuyuki** [comment]
Build looks good. Looking forward to be merged.

**Comment by ishitatsuyuki** [comment]
By the way, here's a recommendation: do the work on master branch, tag it once nightly is released.

**Comment by ishitatsuyuki** [comment]
The cache seems to be \*\*\*\*ed up. Maybe something done wrong in CI configuration?
