### ISSUE TITLE
Does not compile on 1.20.0-nightly (f85579d4a 2017-07-12)

### ISSUE THREAD

**Issue by dtolnay** [Manishearth/rust-clippy#1887]
```
error[E0603]: function `binop_to_string` is private
  --> clippy_lints-0.0.143/src/utils/sugg.rs:11:5
   |
11 | use syntax::print::pprust::binop_to_string;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by dtolnay** [comment]
Relevant upstream change: https://github.com/rust-lang/rust/commit/03431368052effca858cc5aa7dad140948562470 https://github.com/rust-lang/rust/pull/42897.

**Comment by darnir** [comment]
Could we please have a new version released with the above commit?

**Comment by fulara** [comment]
For someone who wants to use the cargo clippy before that next version gets released you can try this command: 
`cargo install clippy --git https://github.com/kraai/rust-clippy --branch fix-build`

**Comment by drusellers** [comment]
Just ran into this as well.

**Comment by thomas-jeepe** [comment]
I ran into this as well, unable to install.

**Comment by blaenk** [comment]
I think the existence of the of the problem has been already confirmed. A workaround was mentioned above.
