### ISSUE TITLE
does not compile on rustc 1.15.0-nightly (d5814b03e 2016-11-23) 

### ISSUE THREAD

**Issue by CSRaghunandan** [Manishearth/rust-clippy#1366]
When I executed `cargo install clippy` I get the below error

```
cargo install clippy
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling quine-mc_cluskey v0.2.4
   Compiling rustc-serialize v0.3.21
   Compiling regex-syntax v0.3.9
   Compiling nom v1.2.4
   Compiling matches v0.1.4
   Compiling semver v0.2.3
   Compiling unicode-normalization v0.1.2
   Compiling toml v0.1.30
   Compiling clippy_lints v0.0.102
error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
  --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/utils/hir.rs:84:15
   |
84 |             (&ExprBreak(li), &ExprBreak(ri)) => both(&li, &ri, |l, r| l.node.as_str() == r.node.as_str()),
   |               ^^^^^^^^^^^^^ expected 2 fields, found 1

error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
  --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/utils/hir.rs:84:31
   |
84 |             (&ExprBreak(li), &ExprBreak(ri)) => both(&li, &ri, |l, r| l.node.as_str() == r.node.as_str()),
   |                               ^^^^^^^^^^^^^ expected 2 fields, found 1

error[E0023]: this pattern has 2 fields, but the corresponding tuple variant has 3 fields
   --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/utils/hir.rs:101:15
    |
101 |             (&ExprLoop(ref lb, ref ll), &ExprLoop(ref rb, ref rl)) => {
    |               ^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 fields, found 2

error[E0023]: this pattern has 2 fields, but the corresponding tuple variant has 3 fields
   --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/utils/hir.rs:101:42
    |
101 |             (&ExprLoop(ref lb, ref ll), &ExprLoop(ref rb, ref rl)) => {
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 fields, found 2

error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
   --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/utils/hir.rs:347:13
    |
347 |             ExprBreak(i) => {
    |             ^^^^^^^^^^^^ expected 2 fields, found 1

error[E0023]: this pattern has 2 fields, but the corresponding tuple variant has 3 fields
   --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/utils/hir.rs:407:13
    |
407 |             ExprLoop(ref b, ref i) => {
    |             ^^^^^^^^^^^^^^^^^^^^^^ expected 3 fields, found 2

error[E0308]: mismatched types
   --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/utils/hir.rs:348:37
    |
348 |                 let c: fn(_) -> _ = ExprBreak;
    |                                     ^^^^^^^^^ incorrect number of function parameters
    |
    = note: expected type `fn(_) -> _`
    = note:    found type `fn(core::option::Option<syntax::codemap::Spanned<syntax::ast::Symbol>>, core::option::Option<syntax::ptr::P<rustc::hir::Expr>>) -> rustc::hir::Expr_ {rustc::hir::Expr_::ExprBreak}`

error[E0308]: mismatched types
   --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/utils/hir.rs:408:40
    |
408 |                 let c: fn(_, _) -> _ = ExprLoop;
    |                                        ^^^^^^^^ incorrect number of function parameters
    |
    = note: expected type `fn(_, _) -> _`
    = note:    found type `fn(syntax::ptr::P<rustc::hir::Block>, core::option::Option<syntax::codemap::Spanned<syntax::ast::Symbol>>, rustc::hir::LoopSource) -> rustc::hir::Expr_ {rustc::hir::Expr_::ExprLoop}`

error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
   --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/utils/inspector.rs:288:9
    |
288 |         hir::ExprBreak(_) => println!("{}Break, {}", ind, ty),
    |         ^^^^^^^^^^^^^^^^^ expected 2 fields, found 1

error[E0023]: this pattern has 2 fields, but the corresponding tuple variant has 3 fields
   --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/utils/higher.rs:144:13
    |
140 |     if_let_chain! {[
    |     - in this macro invocation
...
144 |         let hir::ExprLoop(ref block, _) = arms[0].body.node,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 fields, found 2

error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
   --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/attrs.rs:194:25
    |
194 |         ExprRet(None) | ExprBreak(_) => false,
    |                         ^^^^^^^^^^^^ expected 2 fields, found 1

error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
   --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/eval_order_dependence.rs:127:13
    |
127 |             ExprBreak(_) |
    |             ^^^^^^^^^^^^ expected 2 fields, found 1

error[E0023]: this pattern has 2 fields, but the corresponding tuple variant has 3 fields
   --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/loops.rs:318:16
    |
318 |         if let ExprLoop(ref block, _) = expr.node {
    |                ^^^^^^^^^^^^^^^^^^^^^^ expected 3 fields, found 2

error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
   --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/loops.rs:914:9
    |
914 |         ExprBreak(None) => true,
    |         ^^^^^^^^^^^^^^^ expected 2 fields, found 1

error[E0023]: this pattern has 2 fields, but the corresponding tuple variant has 3 fields
   --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/shadow.rs:281:9
    |
281 |         ExprLoop(ref block, _) => check_block(cx, block, bindings),
    |         ^^^^^^^^^^^^^^^^^^^^^^ expected 3 fields, found 2

error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
  --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/unused_label.rs:67:13
   |
67 |             hir::ExprBreak(Some(label)) |
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 fields, found 1

error[E0023]: this pattern has 2 fields, but the corresponding tuple variant has 3 fields
  --> /Users/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.102/src/unused_label.rs:71:13
   |
71 |             hir::ExprLoop(_, Some(label)) |
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 fields, found 2

error: aborting due to 17 previous errors

error: failed to compile `clippy v0.0.102`, intermediate artifacts can be found at `/var/folders/bf/_hhccrwn69zc56z5nxd35fcm0000gn/T/cargo-install.6fTSR8WBives`

Caused by:
  Could not compile `clippy_lints`.

To learn more, run the command again with --verbose.
```

**Comment by oli-obk** [comment]
I'm on it

**Comment by oli-obk** [comment]
published 0.0.103

**Comment by CSRaghunandan** [comment]
That was a very quick fix.
Thank you 👍
