### ISSUE TITLE
Fails to build with rustc 1.20.0-nightly (067971139 2017-07-02)

### ISSUE THREAD

**Issue by Frederick888** [Manishearth/rust-clippy#1867]
Trying to install clippy with rustup in Linux and got this:

    $ cargo install clippy -f
        Updating registry `https://github.com/rust-lang/crates.io-index`
      Installing clippy v0.0.141
      Compiling semver-parser v0.7.0
      Compiling unicode-xid v0.0.4
      Compiling quine-mc_cluskey v0.2.4
      Compiling serde v1.0.9
      Compiling either v1.1.0
      Compiling lazy_static v0.2.8
      Compiling quote v0.3.15
      Compiling dtoa v0.4.1
      Compiling itoa v0.3.1
      Compiling unicode-normalization v0.1.5
      Compiling num-traits v0.1.39
      Compiling regex-syntax v0.4.1
      Compiling matches v0.1.6
      Compiling synom v0.11.3
      Compiling itertools v0.6.0
      Compiling syn v0.11.11
      Compiling semver v0.6.0
      Compiling serde_json v1.0.2
      Compiling toml v0.4.2
      Compiling serde_derive_internals v0.15.1
      Compiling serde_derive v1.0.9
      Compiling clippy_lints v0.0.141
      Compiling cargo_metadata v0.2.1
      Compiling clippy v0.0.141
    error[E0369]: binary operation `>` cannot be applied to type `rustc::session::CompileIncomplete`
      --> /home/frederick/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.141/src/main.rs:282:20
        |
    282 |                 if err_count > 0 {
        |                    ^^^^^^^^^^^^^
        |
        = note: an implementation of `std::cmp::PartialOrd` might be missing for `rustc::session::CompileIncomplete`

    error: aborting due to previous error

    error: failed to compile `clippy v0.0.141`, intermediate artifacts can be found at `/tmp/cargo-install.NzDKy1P9xxuM`

    Caused by:
      Could not compile `clippy`.

    To learn more, run the command again with --verbose.

```
$ rustc --version
rustc 1.20.0-nightly (067971139 2017-07-02)
```

```
$ cargo --version 
cargo 0.21.0-nightly (4c0a8b63d 2017-06-27)
```

Caused by rust-lang/rust#43015 ?
