### ISSUE TITLE
Does not compile on rustc 1.15.0-nightly (ac635aa95 2016-11-18)

### ISSUE THREAD

**Issue by dtolnay** [Manishearth/rust-clippy#1350]
```
$ cargo build
   Compiling clippy_lints v0.0.99
error[E0308]: mismatched types
  --> clippy_lints/src/len_zero.rs:71:86
   |
71 |             ItemImpl(_, _, _, None, _, ref impl_items) => check_impl_items(cx, item, impl_items),
   |                                                                                      ^^^^^^^^^^ expected slice, found struct `syntax::ptr::P`
   |
   = note: expected type `&[rustc::hir::ImplItem]`
   = note:    found type `&syntax::ptr::P<[rustc::hir::ImplItemRef]>`

error: aborting due to previous error

error: Could not compile `clippy_lints`.

To learn more, run the command again with --verbose.

$ rustc --version
rustc 1.15.0-nightly (ac635aa95 2016-11-18)
```

**Comment by dtolnay** [comment]
Looks like https://github.com/rust-lang/rust/pull/37660 is the culprit.

**Comment by mcarton** [comment]
Thanks, I'm presenting Clippy at [Capitole du Libre](https://2016.capitoledulibre.org/) in 14h, that would have been embarrassing :sweat_smile:

**Comment by oli-obk** [comment]
Wheee, go @mcarton go
